################
# Localization #
################

# FILE NAMES
SERVANT_LIBRARY = "servant_library.fgoc"

# CLASSES

SABER       = "Saber"
ARCHER      = "Archer"
LANCER      = "Lancer"
RIDER       = "Rider"
CASTER      = "Caster"
ASSASSIN    = "Assassin"
BERSERKER   = "Berserker"
RULER       = "Ruler"
AVENGER     = "Avenger"
MOON_CANCER = "Moon Cancer"
ALTER_EGO   = "Alter Ego"
FOREIGNER   = "Foreigner"
SHIELDER    = "Shielder"

# Pieces and Monuments

PIECE = "Piece"

PIECE_SABER         = SABER     + " " + PIECE
PIECE_ARCHER        = ARCHER    + " " + PIECE
PIECE_LANCER        = LANCER    + " " + PIECE
PIECE_RIDER         = RIDER     + " " + PIECE
PIECE_CASTER        = CASTER    + " " + PIECE
PIECE_ASSASSIN      = ASSASSIN  + " " + PIECE
PIECE_BERSERKER     = BERSERKER + " " + PIECE

MONUMENT = "Monument"

MONUMENT_SABER      = SABER     + " " + MONUMENT
MONUMENT_ARCHER     = ARCHER    + " " + MONUMENT
MONUMENT_LANCER     = LANCER    + " " + MONUMENT
MONUMENT_RIDER      = RIDER     + " " + MONUMENT
MONUMENT_CASTER     = CASTER    + " " + MONUMENT
MONUMENT_ASSASSIN   = ASSASSIN  + " " + MONUMENT
MONUMENT_BERSERKER  = BERSERKER + " " + MONUMENT

# Gems

GEM = "Gem of "

GEM_SABER               = GEM + SABER
GEM_ARCHER              = GEM + ARCHER
GEM_LANCER              = GEM + LANCER
GEM_RIDER               = GEM + RIDER
GEM_CASTER              = GEM + CASTER
GEM_ASSASSIN            = GEM + ASSASSIN
GEM_BERSERKER           = GEM + BERSERKER

GEM_MAGIC = "Magic Gem of "

GEM_MAGIC_SABER         = GEM_MAGIC + SABER
GEM_MAGIC_ARCHER        = GEM_MAGIC + ARCHER
GEM_MAGIC_LANCER        = GEM_MAGIC + LANCER
GEM_MAGIC_RIDER         = GEM_MAGIC + RIDER
GEM_MAGIC_CASTER        = GEM_MAGIC + CASTER
GEM_MAGIC_ASSASSIN      = GEM_MAGIC + ASSASSIN
GEM_MAGIC_BERSERKER     = GEM_MAGIC + BERSERKER

GEM_SECRET = "Secret Gem of "

GEM_SECRET_SABER         = GEM_SECRET + SABER
GEM_SECRET_ARCHER        = GEM_SECRET + ARCHER
GEM_SECRET_LANCER        = GEM_SECRET + LANCER
GEM_SECRET_RIDER         = GEM_SECRET + RIDER
GEM_SECRET_CASTER        = GEM_SECRET + CASTER
GEM_SECRET_ASSASSIN      = GEM_SECRET + ASSASSIN
GEM_SECRET_BERSERKER     = GEM_SECRET + BERSERKER

# Materials

BRONZE_00   = "Proof of Hero"
BRONZE_01   = "Evil Bone"
BRONZE_02   = "Dragon Fang"
BRONZE_03   = "Void's Dust"
BRONZE_04   = "Fool's Chain"
BRONZE_05   = "Deadly Poisonous Needle"
BRONZE_06   = "Mystic Spinal Fluid"
BRONZE_07   = "Stake of Wailing Night"
BRONZE_08   = "Mystic Gunpowder"

SILVER_00   = "Seed of Yggdrasil"
SILVER_01   = "Ghost Lantern"
SILVER_02   = "Octuplet Crystals"
SILVER_03   = "Serpent Jewel"
SILVER_04   = "Phoenix Feather"
SILVER_05   = "Eternal Gear"
SILVER_06   = "Forbidden Page"
SILVER_07   = "Homunculus Baby"
SILVER_08   = "Meteor Horseshoe"
SILVER_09   = "Great Knight Medal"
SILVER_10   = "Shell of Reminiscence"
SILVER_11   = "Refined Magatama"
SILVER_12   = "Eternal Ice"
SILVER_13   = "Giant's Ring"
SILVER_14   = "Aurora Steel"
SILVER_15   = "Ancient Bell of Tranquility"
SILVER_16   = "Arrowhead of Sin"
SILVER_17   = "Crown of Radiant Silver"
SILVER_18   = "Divine Spiricle Vein"

GOLD_00     = "Claw of Chaos"
GOLD_01     = "Heart of the Foreign God"
GOLD_02     = "Dragon's Reverse Scale"
GOLD_03     = "Spirit Root"
GOLD_04     = "Warhorse's Young Horn"
GOLD_05     = "Tearstone of Blood"
GOLD_06     = "Black Beast Grease"
GOLD_07     = "Lamp of Evil-Sealing"
GOLD_08     = "Scarab of Wisdom"
GOLD_09     = "Primordial Lanugo"
GOLD_10     = "Cursed Beast Gallstone"
GOLD_11     = "Mysterious Divine Wine"
GOLD_12     = "Dawn's Light Core"
GOLD_13     = "Tsukumo Mirror"
GOLD_14     = "Egg of Truth"
GOLD_15     = "Comet Shard"
GOLD_16     = "Fruit of Longevity"

# Other

OTHER_00    = "QP"
OTHER_01    = "Crystalized Lore"
OTHER_02    = "Holy Grail"
OTHER_03    = "Chaldea Visionary Flames"

################################
# Build Lists and Dictionaries #
################################

CLASSES     = [ SABER, ARCHER, LANCER, RIDER, CASTER, ASSASSIN, BERSERKER, RULER, AVENGER, MOON_CANCER, ALTER_EGO, FOREIGNER, SHIELDER ]

PIECES      = [ PIECE_SABER, PIECE_ARCHER, PIECE_LANCER, PIECE_RIDER, PIECE_CASTER, PIECE_ASSASSIN, PIECE_BERSERKER ]

MONUMENTS   = [ MONUMENT_SABER, MONUMENT_ARCHER, MONUMENT_LANCER, MONUMENT_RIDER, MONUMENT_CASTER, MONUMENT_ASSASSIN, MONUMENT_BERSERKER ]

GEMS        = [ GEM_SABER, GEM_ARCHER, GEM_LANCER, GEM_RIDER, GEM_CASTER, GEM_ASSASSIN, GEM_BERSERKER ]

GEMS_MAGIC  = [ GEM_MAGIC_SABER, GEM_MAGIC_ARCHER, GEM_MAGIC_LANCER, GEM_MAGIC_RIDER, GEM_MAGIC_CASTER, GEM_MAGIC_ASSASSIN, GEM_MAGIC_BERSERKER ]

GEMS_SECRET = [ GEM_SECRET_SABER, GEM_SECRET_ARCHER, GEM_SECRET_LANCER, GEM_SECRET_RIDER, GEM_SECRET_CASTER, GEM_SECRET_ASSASSIN, GEM_SECRET_BERSERKER ]


MATS_BRONZE = [ BRONZE_00, BRONZE_01, BRONZE_02, BRONZE_03, BRONZE_04, BRONZE_05, BRONZE_06, BRONZE_07, BRONZE_08 ]


MATS_SILVER = [ SILVER_00, SILVER_01, SILVER_02, SILVER_03, SILVER_04, SILVER_05, SILVER_06, SILVER_07, SILVER_08, SILVER_09,\
                SILVER_10, SILVER_11, SILVER_12, SILVER_13, SILVER_14, SILVER_15, SILVER_16, SILVER_17, SILVER_18 ]                
    


MATS_GOLD   = [ GOLD_00, GOLD_01, GOLD_02, GOLD_03, GOLD_04, GOLD_05, GOLD_06, GOLD_07, GOLD_08, GOLD_09, \
                GOLD_10, GOLD_11, GOLD_12, GOLD_13, GOLD_14, GOLD_15, GOLD_16 ]           



MATS_OTHER  = [ OTHER_00, OTHER_01, OTHER_02 ]


MATS_ALL_LISTED = [ None, PIECES, MONUMENTS, GEMS, GEMS_MAGIC, GEMS_SECRET, MATS_BRONZE, MATS_SILVER, MATS_GOLD, MATS_OTHER]


MATS_ALL    =  { PIECE_SABER: 100, PIECE_ARCHER: 101, PIECE_LANCER: 102, PIECE_RIDER: 103, PIECE_CASTER: 104, PIECE_ASSASSIN: 105, PIECE_BERSERKER: 106,\
                 100: PIECE_SABER, 101: PIECE_ARCHER, 102: PIECE_LANCER, 103: PIECE_RIDER, 104: PIECE_CASTER, 105: PIECE_ASSASSIN, 106: PIECE_BERSERKER,\
                 \
                 MONUMENT_SABER: 200, MONUMENT_ARCHER: 201, MONUMENT_LANCER: 202, MONUMENT_RIDER: 203, MONUMENT_CASTER: 204, MONUMENT_ASSASSIN: 205, MONUMENT_BERSERKER: 206,\
                 200: MONUMENT_SABER, 201: MONUMENT_ARCHER, 202: MONUMENT_LANCER, 203: MONUMENT_RIDER, 204: MONUMENT_CASTER, 205: MONUMENT_ASSASSIN, 206: MONUMENT_BERSERKER,\
                 \
                 GEM_SABER: 300, GEM_ARCHER: 301, GEM_LANCER: 302, GEM_RIDER: 303, GEM_CASTER: 304, GEM_ASSASSIN: 305, GEM_BERSERKER: 306,\
                 300: GEM_SABER, 301: GEM_ARCHER, 302: GEM_LANCER, 303: GEM_RIDER, 304: GEM_CASTER, 305: GEM_ASSASSIN, 306: GEM_BERSERKER,\
                 \
                 GEM_MAGIC_SABER: 400, GEM_MAGIC_ARCHER: 401, GEM_MAGIC_LANCER: 402, GEM_MAGIC_RIDER: 403, GEM_MAGIC_CASTER: 404, GEM_MAGIC_ASSASSIN: 405, GEM_MAGIC_BERSERKER: 406,\
                 400: GEM_MAGIC_SABER, 401: GEM_MAGIC_ARCHER, 402: GEM_MAGIC_LANCER, 403: GEM_MAGIC_RIDER, 404: GEM_MAGIC_CASTER, 405: GEM_MAGIC_ASSASSIN, 406: GEM_MAGIC_BERSERKER,\
                 \
                 GEM_SECRET_SABER: 500, GEM_SECRET_ARCHER: 501, GEM_SECRET_LANCER: 502, GEM_SECRET_RIDER: 503, GEM_SECRET_CASTER: 504, GEM_SECRET_ASSASSIN: 505, GEM_SECRET_BERSERKER: 506,\
                 500: GEM_SECRET_SABER, 501: GEM_SECRET_ARCHER, 502: GEM_SECRET_LANCER, 503: GEM_SECRET_RIDER, 504: GEM_SECRET_CASTER, 505: GEM_SECRET_ASSASSIN, 506: GEM_SECRET_BERSERKER,\
                 \
                 BRONZE_00: 600, BRONZE_01: 601, BRONZE_02: 602, BRONZE_03: 603, BRONZE_04: 604, BRONZE_05: 605, BRONZE_06: 606, BRONZE_07: 607, BRONZE_08: 608,\
                 600: BRONZE_00, 601: BRONZE_01, 602: BRONZE_02, 603: BRONZE_03, 604: BRONZE_04, 605: BRONZE_05, 606: BRONZE_06, 607: BRONZE_07, 608: BRONZE_08,\
                 \
                 SILVER_00: 700, SILVER_01: 701, SILVER_02: 702, SILVER_03: 703, SILVER_04: 704, SILVER_05: 705, SILVER_06: 706, SILVER_07: 707, SILVER_08: 708, SILVER_09: 709,\
                 SILVER_10: 711, SILVER_11: 712, SILVER_12: 713, SILVER_13: 714, SILVER_14: 715, SILVER_15: 716, SILVER_16: 717, SILVER_17: 718, SILVER_18: 719,\
                 700: SILVER_00, 701: SILVER_01, 702: SILVER_02, 703: SILVER_03, 704: SILVER_04, 705: SILVER_05, 706: SILVER_06, 707: SILVER_07, 708: SILVER_08, 709: SILVER_09,\
                 710: SILVER_10, 711: SILVER_11, 712: SILVER_12, 713: SILVER_13, 714: SILVER_14, 715: SILVER_15, 716: SILVER_16, 717: SILVER_17, 718: SILVER_18,\
                 \
                 GOLD_00: 800, GOLD_01: 801, GOLD_02: 802, GOLD_03: 803, GOLD_04: 804, GOLD_05: 805, GOLD_06: 806, GOLD_07: 807, GOLD_08: 808, GOLD_09: 809,\
                 GOLD_10: 810, GOLD_11: 811, GOLD_12: 812, GOLD_13: 813, GOLD_14: 814, GOLD_15: 815, GOLD_16: 816,\
                 800: GOLD_00, 801: GOLD_01, 802: GOLD_02, 803: GOLD_03, 804: GOLD_04, 805: GOLD_05, 806: GOLD_06, 807: GOLD_07, 808: GOLD_08, 809: GOLD_09,\
                 810: GOLD_10, 811: GOLD_11, 812: GOLD_12, 813: GOLD_13, 814: GOLD_14, 815: GOLD_15, 816: GOLD_16,\
                 \
                 OTHER_00: 900, OTHER_01: 901, OTHER_02: 902, OTHER_03: 903,\
                 900: OTHER_00, 901: OTHER_01, 902: OTHER_02, 903: OTHER_03 }


    